http:
  port: 8080
apiEndpoints:
  user:
    host: localhost
    paths: 
      - '/users*'
      - '/auth*'
serviceEndpoints:
  httpuser:
    url: 'http://localhost:1001'
policies:
  - log
  - proxy
  - jwt
  - request-transformer
  # - basic-auth
  # - cors
  # - expression
  # - key-auth
  # - log
  # - oauth2
  # - proxy
  # - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - log:
        - action:
              message: 'header===> ${req.headers.authorization}'
      - jwt:
        - action:
              secretOrPublicKey: 'jshnfhckwdczkjs'
              checkCredentialExistence: false
              # passThrough: true
      - proxy:
        - action:
              serviceEndpoint: httpuser 
              changeOrigin: true

      