exports.data = {
  role:
  [
    {
      value: 'ADMIN',
      text: 'Quản trị viên',
      active: true,
    },
    {
      value: 'CASHBACK_ADMIN',
      text: 'Quản trị viên cashback',
      active: true,
    },
    {
      value: 'EXECUTE',
      text: 'Nhân viên quản lý',
      active: true,
    },
    {
      value: 'CUSTOMER',
      text: 'Khách hàng',
      active: true,
    },
    {
      value: 'BRAND',
      text: 'Thương hiệu',
      active: true,
    },
  ],
  user:
  [
    {
      avatar: null,
      fullName: 'Admin Cashback',
      birthday: null,
      gender: 1,
      userName: 'admincashback',
      phone: '0000000000',
      password: '$2a$10$y6SU8dMEg.rRSZxWCM7VMeWf3YbFph4zyE/drO.5M1ppX/JPJCKLy',
      email: 'adminCashback@gmail.com',
      country: null,
      typeIdCard: 'CARD',
      dateOfIssue: null,
      role: 'CASHBACK_ADMIN',
      placeOfIssue: null,
      numberIdentify: null,
      imageIdentify: {
        front: null,
        backside: null,
      },
    },
    {
      avatar: null,
      fullName: 'Admin',
      birthday: null,
      gender: 1,
      userName: 'admin',
      phone: '0938803794',
      password: '$2a$10$y6SU8dMEg.rRSZxWCM7VMeWf3YbFph4zyE/drO.5M1ppX/JPJCKLy',
      email: 'admin@gmail.com',
      country: null,
      typeIdCard: 'CARD',
      dateOfIssue: null,
      role: 'ADMIN',
      placeOfIssue: null,
      numberIdentify: null,
      imageIdentify: {
        front: null,
        backside: null,
      },
    },
    {
      avatar: null,
      fullName: 'Supper Admin',
      birthday: null,
      gender: 1,
      userName: 'superAdmin',
      phone: '0999999999',
      password: '$2a$10$y6SU8dMEg.rRSZxWCM7VMeWf3YbFph4zyE/drO.5M1ppX/JPJCKLy',
      email: 'supperAdmin@gmail.com',
      country: null,
      typeIdCard: 'CARD',
      dateOfIssue: null,
      role: 'ADMIN',
      placeOfIssue: null,
      numberIdentify: null,
      imageIdentify: {
        front: null,
        backside: null,
      },
    },
    {
      avatar: null,
      fullName: 'Nhân Viên Quản Lý',
      birthday: null,
      gender: 1,
      phone: '0123456789',
      userName: 'execute',
      password: '$2a$10$6uazoAY3SnEsZQsURQ2EW.9SsefV.NJ5hKdbNl6QzaBumwUR5QB76',
      email: 'execute@gmail.com',
      country: null,
      typeIdCard: 'CARD',
      role: 'EXECUTE',
      dateOfIssue: null,
      placeOfIssue: null,
      numberIdentify: null,
      imageIdentify: {
        front: null,
        backside: null,
      },
    }, {
      avatar: null,
      fullName: 'Khách Hàng 01',
      birthday: null,
      gender: 1,
      userName: 'customer',
      phone: '0123123123',
      password: '$2a$10$W3MLL/TGns9T4IacwdO9v.u8P6wghHVEXoFM3TvlX7Q59m6Z3F8xy',
      email: 'customer01@gmail.com',
      country: null,
      typeIdCard: 'CARD',
      role: 'CUSTOMER',
      dateOfIssue: null,
      placeOfIssue: null,
      numberIdentify: null,
      imageIdentify: {
        front: null,
        backside: null,
      },
    },
  ],
};
